/**
 * A tiny, dependency-free PDF document builder that flows text down a page and
 * breaks to new pages automatically. Uncompressed Helvetica / Helvetica-Bold with
 * accurate glyph widths (embedded AFM metrics) so wrapping is correct. The
 * cross-reference offsets are computed from the actual serialized bytes.
 *
 * Rich enough for structured documents (headings, key/value rows, bullet lists,
 * rules) such as meeting minutes — not just single-page tables (see `pdf.ts`).
 */

export type RGB = [number, number, number];

// AFM advance widths (per 1000 em) for ASCII 32..126. Index = charCode - 32.
// prettier-ignore
const HELVETICA: number[] = [
  278,278,355,556,556,889,667,191,333,333,389,584,278,333,278,278,556,556,556,556,556,556,556,556,556,556,278,278,584,584,584,556,
  1015,667,667,722,722,667,611,778,722,278,500,667,556,833,722,778,667,778,722,667,611,722,667,944,667,667,611,278,278,278,469,556,
  333,556,556,500,556,556,278,556,556,222,222,500,222,833,556,556,556,556,333,500,278,556,500,722,500,500,500,334,260,334,584,
];
// prettier-ignore
const HELVETICA_BOLD: number[] = [
  278,333,474,556,556,889,722,238,333,333,389,584,278,333,278,278,556,556,556,556,556,556,556,556,556,556,333,333,584,584,584,611,
  975,722,722,722,722,667,611,778,722,278,556,722,611,833,722,778,667,778,722,667,611,722,667,944,667,667,611,333,278,333,584,556,
  333,556,611,556,611,556,333,611,611,278,278,556,278,889,611,611,611,611,389,556,333,611,556,778,556,556,500,389,280,389,584,
];

// Common typographic characters mapped to their WinAnsi byte + AFM widths (Helvetica, Bold).
// Lets the document use real middots, dashes, quotes and ellipsis instead of "?".
const WINANSI: Record<number, { byte: number; w: number; wb: number }> = {
  0x00b7: { byte: 0xb7, w: 278, wb: 278 }, // ·
  0x2013: { byte: 0x96, w: 556, wb: 556 }, // –
  0x2014: { byte: 0x97, w: 1000, wb: 1000 }, // —
  0x2022: { byte: 0x95, w: 350, wb: 350 }, // •
  0x2026: { byte: 0x85, w: 1000, wb: 1000 }, // …
  0x2018: { byte: 0x91, w: 222, wb: 278 }, // ‘
  0x2019: { byte: 0x92, w: 222, wb: 278 }, // ’
  0x201c: { byte: 0x93, w: 333, wb: 500 }, // “
  0x201d: { byte: 0x94, w: 333, wb: 500 }, // ”
  0x00a0: { byte: 0x20, w: 278, wb: 278 }, // nbsp → space
};

/**
 * Escape a string for a PDF text literal. ASCII passes through (with ()\ escaped);
 * a small set of common typographic characters is remapped to WinAnsi bytes so they
 * render; anything else becomes "?". Every output char is one byte in latin1, so the
 * string length still equals the serialized byte length (keeps /Length correct).
 */
function escapePdfText(s: string): string {
  let out = '';
  for (const ch of s) {
    const code = ch.codePointAt(0)!;
    if (code >= 0x20 && code <= 0x7e) {
      if (ch === '\\' || ch === '(' || ch === ')') out += '\\';
      out += ch;
    } else if (WINANSI[code]) {
      out += String.fromCharCode(WINANSI[code]!.byte);
    } else if (code >= 0xa1 && code <= 0xff) {
      out += ch; // Latin-1 aligns with WinAnsi in this range
    } else {
      out += '?';
    }
  }
  return out;
}

/** Format a number for PDF content ops: fixed precision, trailing zeros trimmed. */
function num(n: number): string {
  let s = n.toFixed(2);
  if (s.includes('.')) s = s.replace(/0+$/, '').replace(/\.$/, '');
  return s;
}

const INK: RGB = [0.11, 0.1, 0.09];
const MUTED: RGB = [0.42, 0.4, 0.38];
const BRAND: RGB = [0.66, 0.12, 0.12];
const LINE: RGB = [0.82, 0.8, 0.78];

/** Parse "#RRGGBB" (or an [r,g,b] 0-1 triple) into an RGB 0-1 triple. */
export function hexToRgb(input: string | RGB, fallback: RGB = INK): RGB {
  if (Array.isArray(input)) return input;
  const m = /^#?([0-9a-f]{6})$/i.exec(input.trim());
  if (!m) return fallback;
  const n = parseInt(m[1]!, 16);
  return [((n >> 16) & 0xff) / 255, ((n >> 8) & 0xff) / 255, (n & 0xff) / 255];
}

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}
function mix(a: RGB, b: RGB, t: number): RGB {
  return [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)];
}
/** Darken an RGB toward black by `amount` (0-1). */
function darken(c: RGB, amount: number): RGB {
  return [c[0] * (1 - amount), c[1] * (1 - amount), c[2] * (1 - amount)];
}

export interface TextOptions {
  bold?: boolean;
  size?: number;
  color?: RGB;
  /** Left indent from the content edge, in points. */
  indent?: number;
  /** Extra vertical space added after the block, in points. */
  gap?: number;
}

export interface PdfDocumentOptions {
  /** Small line shown at the bottom-left of every page (e.g. a "generated by" credit). */
  footerLeft?: string;
  /** Brand palette; hex strings or RGB triples. Drives headings, rules, labels and the footer. */
  palette?: Partial<Record<'ink' | 'muted' | 'brand' | 'line', string | RGB>>;
}

export class PdfDocument {
  readonly pageWidth = 612; // US Letter
  readonly pageHeight = 792;
  readonly margin = 54; // 0.75"
  readonly bottomMargin = 56; // leaves room for the footer

  private pages: string[][] = [];
  private ops: string[] = [];
  private y = 0;

  /** Resolved brand palette used by headings, rules, labels and the footer. */
  private readonly pal: { ink: RGB; muted: RGB; brand: RGB; line: RGB };

  constructor(private readonly opts: PdfDocumentOptions = {}) {
    const p = opts.palette ?? {};
    this.pal = {
      ink: p.ink ? hexToRgb(p.ink, INK) : INK,
      muted: p.muted ? hexToRgb(p.muted, MUTED) : MUTED,
      brand: p.brand ? hexToRgb(p.brand, BRAND) : BRAND,
      line: p.line ? hexToRgb(p.line, LINE) : LINE,
    };
    this.newPage();
  }

  private get contentWidth(): number {
    return this.pageWidth - this.margin * 2;
  }

  private newPage(): void {
    this.ops = [];
    this.pages.push(this.ops);
    this.y = this.pageHeight - this.margin;
  }

  private ensure(height: number): void {
    if (this.y - height < this.bottomMargin) this.newPage();
  }

  private charWidth(ch: string, bold: boolean): number {
    const code = ch.codePointAt(0) ?? 63;
    if (code >= 32 && code <= 126) return (bold ? HELVETICA_BOLD : HELVETICA)[code - 32] ?? 556;
    const extra = WINANSI[code];
    if (extra) return bold ? extra.wb : extra.w;
    return 556; // '?' fallback
  }

  /** Width of a string in points at the given size/weight. */
  textWidth(text: string, size: number, bold = false): number {
    let total = 0;
    for (const ch of text) total += this.charWidth(ch, bold);
    return (total / 1000) * size;
  }

  private wrap(text: string, size: number, bold: boolean, maxWidth: number): string[] {
    const words = text.split(/\s+/).filter((w) => w.length > 0);
    if (words.length === 0) return [''];
    const lines: string[] = [];
    let cur = '';
    for (const w of words) {
      const trial = cur ? `${cur} ${w}` : w;
      if (this.textWidth(trial, size, bold) <= maxWidth) {
        cur = trial;
        continue;
      }
      if (cur) lines.push(cur);
      if (this.textWidth(w, size, bold) > maxWidth) {
        // Hard-break a word that is itself wider than the line.
        let chunk = '';
        for (const ch of w) {
          if (chunk && this.textWidth(chunk + ch, size, bold) > maxWidth) {
            lines.push(chunk);
            chunk = ch;
          } else {
            chunk += ch;
          }
        }
        cur = chunk;
      } else {
        cur = w;
      }
    }
    if (cur) lines.push(cur);
    return lines;
  }

  private drawText(text: string, x: number, y: number, size: number, bold: boolean, color: RGB): void {
    this.ops.push(`${num(color[0])} ${num(color[1])} ${num(color[2])} rg`);
    this.ops.push('BT', `/${bold ? 'F2' : 'F1'} ${num(size)} Tf`, `${num(x)} ${num(y)} Td`, `(${escapePdfText(text)}) Tj`, 'ET');
  }

  private drawRect(x: number, y: number, w: number, h: number, color: RGB): void {
    this.ops.push(`${num(color[0])} ${num(color[1])} ${num(color[2])} rg`);
    this.ops.push(`${num(x)} ${num(y)} ${num(w)} ${num(h)} re`, 'f');
  }

  /** Push a rounded-rectangle path (construction only — the caller paints with f / W n). */
  private roundedRectPath(x: number, y: number, w: number, h: number, r: number): void {
    const k = r * 0.5523;
    const p = (a: number, b: number) => `${num(a)} ${num(b)}`;
    this.ops.push(
      `${p(x + r, y + h)} m`,
      `${p(x + w - r, y + h)} l`,
      `${p(x + w - r + k, y + h)} ${p(x + w, y + h - r + k)} ${p(x + w, y + h - r)} c`,
      `${p(x + w, y + r)} l`,
      `${p(x + w, y + r - k)} ${p(x + w - r + k, y)} ${p(x + w - r, y)} c`,
      `${p(x + r, y)} l`,
      `${p(x + r - k, y)} ${p(x, y + r - k)} ${p(x, y + r)} c`,
      `${p(x, y + h - r)} l`,
      `${p(x, y + h - r + k)} ${p(x + r - k, y + h)} ${p(x + r, y + h)} c`,
      'h',
    );
  }

  /** Draw the brand logo mark: a rounded gradient tile with a white check + progress dot. */
  logoMark(x: number, y: number, size: number, from?: RGB, to?: RGB): this {
    const c0 = from ?? this.pal.brand;
    const c1 = to ?? darken(this.pal.brand, 0.4);
    const r = size * 0.22;
    // Gradient tile: clip to the rounded rect, then paint interpolated horizontal bands.
    this.ops.push('q');
    this.roundedRectPath(x, y, size, size, r);
    this.ops.push('W', 'n');
    const bands = 22;
    const bh = size / bands;
    for (let i = 0; i < bands; i++) {
      const col = mix(c0, c1, i / (bands - 1));
      this.drawRect(x, y + size - (i + 1) * bh, size, bh + 0.5, col);
    }
    this.ops.push('Q');
    // White check mark (stroked, round caps).
    this.ops.push('1 1 1 RG', `${num(size * 0.1)} w`, '1 J', '1 j');
    this.ops.push(
      `${num(x + size * 0.27)} ${num(y + size * 0.5)} m`,
      `${num(x + size * 0.43)} ${num(y + size * 0.34)} l`,
      `${num(x + size * 0.72)} ${num(y + size * 0.64)} l`,
      'S',
    );
    // Small white progress node (filled circle) at the top-right.
    const dr = size * 0.07;
    this.roundedRectPath(x + size * 0.72 - dr, y + size * 0.74 - dr, dr * 2, dr * 2, dr);
    this.ops.push('1 1 1 rg', 'f');
    return this;
  }

  /**
   * A branded document header: the logo mark, product name + tagline, an eyebrow label,
   * and a brand rule beneath. Positions itself from the current cursor and advances past it.
   */
  brandHeader(opts: { title: string; subtitle?: string; eyebrow?: string; from?: RGB; to?: RGB }): this {
    const s = 42;
    const top = this.y;
    this.logoMark(this.margin, top - s, s, opts.from, opts.to);
    const tx = this.margin + s + 14;
    if (opts.eyebrow) this.drawText(opts.eyebrow.toUpperCase(), tx, top - 9, 8, true, this.pal.brand);
    this.drawText(opts.title, tx, top - 26, 17, true, this.pal.ink);
    if (opts.subtitle) this.drawText(opts.subtitle, tx, top - 38, 9, false, this.pal.muted);
    this.y = top - s - 12;
    this.drawRect(this.margin, this.y, this.contentWidth, 2, this.pal.brand);
    this.y -= 14;
    return this;
  }

  /** Add empty vertical space (points). */
  spacer(height: number): this {
    this.ensure(height);
    this.y -= height;
    return this;
  }

  /** A flowing paragraph; honors embedded "\n" and wraps to the content width. */
  text(content: string, options: TextOptions = {}): this {
    const size = options.size ?? 10.5;
    const bold = options.bold ?? false;
    const color = options.color ?? this.pal.ink;
    const indent = options.indent ?? 0;
    const leading = size * 1.32;
    const maxWidth = this.contentWidth - indent;
    for (const para of content.split('\n')) {
      const lines = para.length ? this.wrap(para, size, bold, maxWidth) : [''];
      for (const ln of lines) {
        this.ensure(leading);
        this.y -= leading;
        if (ln) this.drawText(ln, this.margin + indent, this.y, size, bold, color);
      }
    }
    if (options.gap) this.y -= options.gap;
    return this;
  }

  /** A section heading: bold, slightly larger, with a hairline rule beneath. */
  heading(text: string, options: { size?: number; color?: RGB; topGap?: number } = {}): this {
    const size = options.size ?? 12.5;
    const topGap = options.topGap ?? 14;
    this.spacer(topGap);
    this.text(text, { bold: true, size, color: options.color ?? this.pal.brand });
    this.y -= 3;
    this.ensure(6);
    this.drawRect(this.margin, this.y, this.contentWidth, 0.7, this.pal.line);
    this.y -= 6;
    return this;
  }

  /** A "Label: value" row; the value wraps under a hanging indent aligned past the label. */
  keyValue(label: string, value: string, options: { size?: number } = {}): this {
    const size = options.size ?? 10.5;
    const leading = size * 1.32;
    const labelText = `${label}  `;
    const labelWidth = this.textWidth(labelText, size, true);
    const valueLines = this.wrap(value || '—', size, false, this.contentWidth - labelWidth);
    valueLines.forEach((ln, i) => {
      this.ensure(leading);
      this.y -= leading;
      if (i === 0) this.drawText(labelText, this.margin, this.y, size, true, this.pal.muted);
      this.drawText(ln, this.margin + labelWidth, this.y, size, false, this.pal.ink);
    });
    return this;
  }

  /** A bullet list item with a hanging indent; a small square marks it. */
  bullet(content: string, options: { indent?: number; color?: RGB; size?: number } = {}): this {
    const size = options.size ?? 10.5;
    const indent = options.indent ?? 0;
    const marker = 12;
    const leading = size * 1.32;
    const maxWidth = this.contentWidth - indent - marker;
    const lines = this.wrap(content, size, false, maxWidth);
    lines.forEach((ln, i) => {
      this.ensure(leading);
      this.y -= leading;
      if (i === 0) this.drawRect(this.margin + indent + 1, this.y + size * 0.28, 2.6, 2.6, options.color ?? this.pal.brand);
      this.drawText(ln, this.margin + indent + marker, this.y, size, false, this.pal.ink);
    });
    return this;
  }

  /** A numbered list item with a hanging indent aligned past the number. */
  numbered(marker: string, content: string, options: { indent?: number; size?: number } = {}): this {
    const size = options.size ?? 10.5;
    const indent = options.indent ?? 0;
    const gutter = Math.max(16, this.textWidth(`${marker} `, size, true) + 4);
    const leading = size * 1.32;
    const lines = this.wrap(content, size, false, this.contentWidth - indent - gutter);
    lines.forEach((ln, i) => {
      this.ensure(leading);
      this.y -= leading;
      if (i === 0) this.drawText(marker, this.margin + indent, this.y, size, true, this.pal.brand);
      this.drawText(ln, this.margin + indent + gutter, this.y, size, false, this.pal.ink);
    });
    return this;
  }

  /** A full-width hairline rule. */
  rule(color?: RGB): this {
    this.spacer(4);
    this.ensure(4);
    this.drawRect(this.margin, this.y, this.contentWidth, 0.6, color ?? this.pal.line);
    this.y -= 4;
    return this;
  }

  /** Serialize to a valid PDF byte buffer. */
  build(): Buffer {
    const total = this.pages.length;
    const footerText = this.opts.footerLeft;

    // Object numbering: 1 Catalog, 2 Pages, 3 Font F1, 4 Font F2, then page/content pairs.
    const objects: string[] = [
      '<< /Type /Catalog /Pages 2 0 R >>',
      '', // Pages (filled below once kids are known)
      '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>',
      '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>',
    ];

    const kids: string[] = [];
    this.pages.forEach((pageOps, i) => {
      const pageObjNum = 5 + i * 2;
      const contentObjNum = 6 + i * 2;
      kids.push(`${pageObjNum} 0 R`);

      const ops = [...pageOps];
      const { line, muted, brand } = this.pal;
      const footerLines = (footerText ?? '').split('\n').filter((l) => l.length > 0);
      // Footer: hairline (with a short brand accent at the left) + credit lines + page number.
      ops.push(`${num(line[0])} ${num(line[1])} ${num(line[2])} rg`);
      ops.push(`${num(this.margin)} 44 ${num(this.contentWidth)} 0.6 re`, 'f');
      ops.push(`${num(brand[0])} ${num(brand[1])} ${num(brand[2])} rg`);
      ops.push(`${num(this.margin)} 44 40 1.6 re`, 'f');
      footerLines.forEach((ln, li) => {
        ops.push(`${num(muted[0])} ${num(muted[1])} ${num(muted[2])} rg`);
        ops.push('BT', '/F1 8 Tf', `${num(this.margin)} ${num(33 - li * 10)} Td`, `(${escapePdfText(ln)}) Tj`, 'ET');
      });
      const pageLabel = `Page ${i + 1} of ${total}`;
      const labelWidth = this.textWidth(pageLabel, 8, false);
      ops.push(`${num(muted[0])} ${num(muted[1])} ${num(muted[2])} rg`);
      ops.push('BT', '/F1 8 Tf', `${num(this.pageWidth - this.margin - labelWidth)} 33 Td`, `(${escapePdfText(pageLabel)}) Tj`, 'ET');

      const stream = ops.join('\n');
      objects[pageObjNum - 1] =
        `<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${this.pageWidth} ${this.pageHeight}] ` +
        `/Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ${contentObjNum} 0 R >>`;
      objects[contentObjNum - 1] = `<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`;
    });

    objects[1] = `<< /Type /Pages /Kids [${kids.join(' ')}] /Count ${total} >>`;

    let pdf = '%PDF-1.4\n';
    const offsets: number[] = [];
    objects.forEach((body, i) => {
      offsets.push(pdf.length);
      pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
    });

    const xrefStart = pdf.length;
    const size = objects.length + 1;
    pdf += `xref\n0 ${size}\n`;
    pdf += '0000000000 65535 f \n';
    for (const off of offsets) pdf += `${String(off).padStart(10, '0')} 00000 n \n`;
    pdf += `trailer\n<< /Size ${size} /Root 1 0 R >>\nstartxref\n${xrefStart}\n%%EOF`;

    return Buffer.from(pdf, 'latin1');
  }
}
