import { describe, it, expect } from 'vitest';
import { PdfDocument, hexToRgb } from './pdf-document';
import { inspectPdf } from './pdf-inspect';

describe('PdfDocument', () => {
  it('produces a valid PDF envelope whose xref offsets point at each object', () => {
    const doc = new PdfDocument();
    doc.heading('Section').bullet('One').bullet('Two').keyValue('Owner', 'Ada Lovelace');
    const buf = doc.build();
    const pdf = buf.toString('latin1');
    expect(pdf.startsWith('%PDF-1.')).toBe(true);
    expect(pdf.trimEnd().endsWith('%%EOF')).toBe(true);
    const startxref = Number(pdf.match(/startxref\s+(\d+)/)![1]);
    expect(pdf.slice(startxref, startxref + 4)).toBe('xref');
    const offsets = [...pdf.matchAll(/^(\d{10}) \d{5} n $/gm)].map((m) => Number(m[1]));
    expect(offsets.length).toBeGreaterThan(5);
    offsets.forEach((off, i) => {
      expect(pdf.slice(off, off + `${i + 1} 0 obj`.length)).toBe(`${i + 1} 0 obj`);
    });
    expect(inspectPdf(buf).pages[0]).toEqual(expect.arrayContaining(['Section', 'One', 'Two', 'Owner', 'Ada Lovelace']));
  });

  it('embeds subsetted Unicode fonts (IBM Plex Sans + Noto Naskh Arabic), not WinAnsi Helvetica', () => {
    const doc = new PdfDocument();
    doc.text('Hello world').text('مرحبا بكم');
    const pdf = doc.build().toString('latin1');
    expect(pdf).toMatch(/\/FontName \/[A-Z]{6}\+IBMPlexSans-Regular/);
    expect(pdf).toMatch(/\/FontName \/[A-Z]{6}\+NotoNaskhArabic-Regular/);
    expect(pdf).toContain('/FontFile2');
    expect(pdf).toContain('/ToUnicode');
    expect(pdf).not.toContain('/BaseFont /Helvetica');
  });

  it('keeps Arabic text as Arabic (never "?"), with the logical text recorded for copy/search', () => {
    const doc = new PdfDocument({ title: 'اجتماع' });
    doc.text('اجتماع مراجعة الميزانية', { bold: true, size: 20 }).text('الموعد 10:30 in Room B');
    const { pages } = inspectPdf(doc.build());
    expect(pages[0]).toContain('اجتماع مراجعة الميزانية');
    expect(pages[0]).toContain('الموعد 10:30 in Room B');
    expect(pages[0]!.join('')).not.toContain('?');
  });

  it('flows onto multiple pages and numbers them "Page N of M"', () => {
    const doc = new PdfDocument({ footerLeft: 'Generated by MICO360' });
    for (let i = 0; i < 120; i++) doc.text(`Line number ${i} with enough text to take vertical room on the page.`);
    const buf = doc.build();
    const { pages } = inspectPdf(buf);
    expect(pages.length).toBeGreaterThan(1);
    expect(doc.pageCount).toBe(pages.length);
    expect(pages[0]).toContain(`Page 1 of ${pages.length}`);
    expect(pages[pages.length - 1]).toContain(`Page ${pages.length} of ${pages.length}`);
    expect(pages[1]).toContain('Generated by MICO360');
    // every line made it into the document, in order
    const lines = pages.flat().filter((t) => t.startsWith('Line number'));
    expect(lines).toHaveLength(120);
    expect(lines[119]).toContain('Line number 119');
  });

  it('wraps a long word wider than the line by hard-breaking it', () => {
    const doc = new PdfDocument();
    doc.text('x'.repeat(400));
    const runs = inspectPdf(doc.build()).pages[0]!.filter((t) => /^x+$/.test(t));
    expect(runs.length).toBeGreaterThan(1);
    expect(runs.join('')).toBe('x'.repeat(400));
  });

  it('wraps long paragraphs instead of running off the page edge', () => {
    const doc = new PdfDocument();
    const para = 'Parens ( ) and a backslash \\ must not break anything; '.repeat(12).trim();
    doc.text(para);
    const lines = inspectPdf(doc.build()).pages[0]!.filter((t) => !t.startsWith('Page '));
    expect(lines.length).toBeGreaterThan(2);
    expect(lines.join(' ')).toBe(para);
  });

  it('measures bold text as wider than regular for the same string', () => {
    const doc = new PdfDocument();
    expect(doc.textWidth('Meeting', 12, true)).toBeGreaterThan(doc.textWidth('Meeting', 12, false));
  });

  it('parses hex colors to normalized RGB triples', () => {
    expect(hexToRgb('#8B1E1E')).toEqual([139 / 255, 30 / 255, 30 / 255]);
    expect(hexToRgb('not-a-color', [0, 0, 0])).toEqual([0, 0, 0]);
  });

  it('renders a branded header with a vector logo mark (rounded clip, gradient, check stroke)', () => {
    const doc = new PdfDocument({ palette: { brand: '#0057B8' } });
    doc.brandHeader({ eyebrow: 'Minutes of Meeting', title: 'Acme Tasks', subtitle: 'Get it done' });
    const buf = doc.build();
    const { pages, contents, objects } = inspectPdf(buf);
    expect(pages[0]).toEqual(expect.arrayContaining(['MINUTES OF MEETING', 'Acme Tasks', 'Get it done']));
    const content = contents[0]!;
    expect(content).toMatch(/ c\n/); // bezier corners of the rounded tile
    expect(content).toMatch(/W n/); // clip for the gradient fill
    expect(content).toMatch(/1 1 1 SCN/); // white check stroke
    // the brand color (#0057B8 → 0 0.341 0.722) drives the eyebrow + brand rule fill
    expect(content).toMatch(/0 0\.34\d* 0\.72\d* scn/);
    expect([...objects.values()].some((d) => /\/ShadingType 2/.test(d))).toBe(true); // axial gradient
  });

  it('builds idempotently', () => {
    const doc = new PdfDocument();
    doc.text('Once');
    expect(doc.build()).toBe(doc.build());
  });
});

describe('PdfDocument.table', () => {
  const columns = [{ header: 'Project' }, { header: 'Total' }];

  it('paginates long tables, repeating the header on every page and keeping every row', () => {
    const rows = Array.from({ length: 150 }, (_, i) => [i % 2 ? `مشروع رقم ${i}` : `Project ${i}`, String(i)]);
    const doc = new PdfDocument();
    doc.table(columns, rows);
    const { pages } = inspectPdf(doc.build());
    expect(pages.length).toBeGreaterThanOrEqual(3);
    for (const p of pages) expect(p.slice(0, 2)).toEqual(['Project', 'Total']);
    const cells = pages.flat();
    for (let i = 0; i < 150; i++) {
      expect(cells).toContain(i % 2 ? `مشروع رقم ${i}` : `Project ${i}`);
      expect(cells).toContain(String(i));
    }
  });

  it('wraps a long cell inside its column instead of overflowing', () => {
    const long = 'A very long description that certainly does not fit on a single line of a narrow column in the table';
    const doc = new PdfDocument();
    doc.table([{ header: 'Id' }, { header: 'Description' }, { header: 'Owner' }], [['1', long + ' ' + long, 'Ada']]);
    const cells = inspectPdf(doc.build()).pages[0]!;
    const descLines = cells.filter((t) => !['Id', 'Description', 'Owner', '1', 'Ada', 'Page 1 of 1'].includes(t));
    expect(descLines.length).toBeGreaterThan(1);
    expect(descLines.join(' ')).toBe(long + ' ' + long);
  });
});

describe('PdfDocument — report layout', () => {
  it('lays out landscape A4 pages when asked', () => {
    const doc = new PdfDocument({ orientation: 'landscape' });
    doc.text('Wide');
    const pdf = doc.build().toString('latin1');
    expect(pdf).toMatch(/\/MediaBox \[0 0 841\.89 595\.28\]/);
  });

  it('puts the company logo (an embedded PNG) and the title in the report header', () => {
    const doc = new PdfDocument();
    doc.reportHeader({ title: 'Tasks report', subtitle: 'MICO360 Platform', details: ['Generated 1 Oct 2026, 09:00'] });
    const buf = doc.build();
    const { pages, objects } = inspectPdf(buf);
    expect(pages[0]).toEqual(expect.arrayContaining(['Tasks report', 'MICO360 Platform', 'Generated 1 Oct 2026, 09:00']));
    expect([...objects.values()].some((d) => /\/Subtype \/Image/.test(d) && /\/Width 900/.test(d))).toBe(true);
    // Headings and titles are set in Archivo, the web app's display face.
    expect(buf.toString('latin1')).toMatch(/\/FontName \/[A-Z]{6}\+Archivo-Bold/);
  });

  it('repeats a slim header (logo + title) on every page after the first', () => {
    const doc = new PdfDocument({ runningTitle: 'Tasks report · MICO360 Platform' });
    doc.reportHeader({ title: 'Tasks report' });
    for (let i = 0; i < 120; i++) doc.text(`Line ${i}`);
    const { pages, contents } = inspectPdf(doc.build());
    expect(pages.length).toBeGreaterThan(1);
    for (let p = 1; p < pages.length; p++) {
      expect(pages[p]).toContain('Tasks report · MICO360 Platform');
      expect(contents[p]).toMatch(/\/I\d+ Do/); // the logo image is drawn
    }
    // Body text never runs under the running header: every line is still there exactly once.
    const all = pages.flat().filter((t) => t.startsWith('Line '));
    expect(all).toHaveLength(120);
  });

  it('draws stat tiles with their values and labels', () => {
    const doc = new PdfDocument();
    doc.statTiles([{ label: 'Total tasks', value: '42' }, { label: 'Completed', value: '27', note: '64%' }, { label: 'Overdue', value: '5', tone: 'danger' }]);
    expect(inspectPdf(doc.build()).pages[0]).toEqual(expect.arrayContaining(['42', 'Total tasks', '27', 'Completed', '64%', '5', 'Overdue']));
  });

  it('draws a bar list with labels and values, scaled to the largest', () => {
    const doc = new PdfDocument();
    doc.barList([{ label: 'Done', value: 12 }, { label: 'In progress', value: 6 }, { label: 'مراجعة', value: 0 }]);
    expect(inspectPdf(doc.build()).pages[0]).toEqual(expect.arrayContaining(['Done', '12', 'In progress', '6', 'مراجعة', '0']));
  });

  it('draws a line chart with a legend and axis labels', () => {
    const doc = new PdfDocument();
    doc.lineChart({
      labels: ['2026-09-01', '2026-09-02', '2026-09-03', '2026-09-04'],
      series: [
        { name: 'Created', values: [1, 3, 2, 4] },
        { name: 'Completed', values: [0, 2, 2, 5] },
      ],
    });
    const { pages, contents } = inspectPdf(doc.build());
    // Max 5 → an axis of 0, 2, 4, 6, 8.
    expect(pages[0]).toEqual(expect.arrayContaining(['Created', 'Completed', '2026-09-01', '2026-09-04', '0', '4', '8']));
    expect(contents[0]).toMatch(/ l\n/); // polylines
  });

  it('keeps a block whole: a chart that does not fit starts a new page', () => {
    const doc = new PdfDocument();
    for (let i = 0; i < 44; i++) doc.text(`Filler ${i}`);
    doc.lineChart({ labels: ['a', 'b'], series: [{ name: 'Series', values: [1, 2] }] });
    const { pages } = inspectPdf(doc.build());
    expect(pages.length).toBe(2);
    expect(pages[1]).toContain('Series');
  });
});

describe('PdfDocument — no clipping, no orphans', () => {
  it('never cuts a tile note short: one that does not fit beside the value gets its own line', () => {
    const doc = new PdfDocument();
    doc.statTiles([1, 2, 3, 4].map((i) => ({ label: `Tile ${i}`, value: '100%', note: '129 on time · 46 late' })));
    expect(inspectPdf(doc.build()).pages[0]!.filter((t) => t === '129 on time · 46 late')).toHaveLength(4);
  });

  it('never cuts a tile value short: long values shrink to fit, and wrap if they still do not', () => {
    const doc = new PdfDocument();
    doc.statTiles([
      { label: 'Status', value: 'In progress' },
      { label: 'Due', value: '30 Sep 2026' },
      { label: 'Project', value: 'Rig Inspection Portal maintenance programme' },
      { label: 'Progress', value: '40%' },
    ]);
    const text = inspectPdf(doc.build()).pages[0]!;
    expect(text).toEqual(expect.arrayContaining(['In progress', '30 Sep 2026', '40%']));
    expect(text.join(' ')).toContain('Rig Inspection Portal maintenance programme');
  });

  it('keeps a heading with the block after it (keepWith), instead of leaving it alone at a page end', () => {
    const doc = new PdfDocument();
    for (let i = 0; i < 40; i++) doc.text(`Filler ${i}`);
    doc.heading('Completion trend', { keepWith: 200 });
    doc.lineChart({ labels: ['a', 'b'], series: [{ name: 'Series', values: [1, 2] }] });
    const { pages } = inspectPdf(doc.build());
    expect(pages[0]).not.toContain('Completion trend');
    expect(pages[1]).toEqual(expect.arrayContaining(['Completion trend', 'Series']));
  });

  it('measures a table before drawing it, so a small one can be kept whole', () => {
    const doc = new PdfDocument();
    const cols = [{ header: 'Project' }, { header: 'Tasks' }];
    const rows = [['A', '1'], ['B', '2'], ['C', '3'], ['D', '4']];
    const h = doc.tableHeight(cols, rows);
    expect(h).toBeGreaterThan(60);
    expect(h).toBeLessThan(140);
  });

  it('colours chosen cells (e.g. overdue dates)', () => {
    const doc = new PdfDocument();
    doc.table([{ header: 'Key' }, { header: 'Due' }], [['MICO-1', '1 Oct 2026 · Overdue']], { cellColor: (r, c) => (c === 1 ? [0.72, 0.16, 0.16] : null) });
    expect(inspectPdf(doc.build()).contents[0]).toMatch(/0\.72\d* 0\.16\d* 0\.16\d* scn/);
  });
});
