import { describe, it, expect } from 'vitest';
import { PdfDocument, hexToRgb } from './pdf-document';
import { inspectPdf } from './pdf-inspect';

describe('PdfDocument', () => {
  it('produces a valid PDF envelope whose xref offsets point at each object', () => {
    const doc = new PdfDocument();
    doc.heading('Section').bullet('One').bullet('Two').keyValue('Owner', 'Ada Lovelace');
    const buf = doc.build();
    const pdf = buf.toString('latin1');
    expect(pdf.startsWith('%PDF-1.')).toBe(true);
    expect(pdf.trimEnd().endsWith('%%EOF')).toBe(true);
    const startxref = Number(pdf.match(/startxref\s+(\d+)/)![1]);
    expect(pdf.slice(startxref, startxref + 4)).toBe('xref');
    const offsets = [...pdf.matchAll(/^(\d{10}) \d{5} n $/gm)].map((m) => Number(m[1]));
    expect(offsets.length).toBeGreaterThan(5);
    offsets.forEach((off, i) => {
      expect(pdf.slice(off, off + `${i + 1} 0 obj`.length)).toBe(`${i + 1} 0 obj`);
    });
    expect(inspectPdf(buf).pages[0]).toEqual(expect.arrayContaining(['Section', 'One', 'Two', 'Owner', 'Ada Lovelace']));
  });

  it('embeds subsetted Unicode fonts (Noto Sans + Noto Naskh Arabic), not WinAnsi Helvetica', () => {
    const doc = new PdfDocument();
    doc.text('Hello world').text('مرحبا بكم');
    const pdf = doc.build().toString('latin1');
    expect(pdf).toMatch(/\/FontName \/[A-Z]{6}\+NotoSans-Regular/);
    expect(pdf).toMatch(/\/FontName \/[A-Z]{6}\+NotoNaskhArabic-Regular/);
    expect(pdf).toContain('/FontFile2');
    expect(pdf).toContain('/ToUnicode');
    expect(pdf).not.toContain('/BaseFont /Helvetica');
  });

  it('keeps Arabic text as Arabic (never "?"), with the logical text recorded for copy/search', () => {
    const doc = new PdfDocument({ title: 'اجتماع' });
    doc.text('اجتماع مراجعة الميزانية', { bold: true, size: 20 }).text('الموعد 10:30 in Room B');
    const { pages } = inspectPdf(doc.build());
    expect(pages[0]).toContain('اجتماع مراجعة الميزانية');
    expect(pages[0]).toContain('الموعد 10:30 in Room B');
    expect(pages[0]!.join('')).not.toContain('?');
  });

  it('flows onto multiple pages and numbers them "Page N of M"', () => {
    const doc = new PdfDocument({ footerLeft: 'Generated by MICO360' });
    for (let i = 0; i < 120; i++) doc.text(`Line number ${i} with enough text to take vertical room on the page.`);
    const buf = doc.build();
    const { pages } = inspectPdf(buf);
    expect(pages.length).toBeGreaterThan(1);
    expect(doc.pageCount).toBe(pages.length);
    expect(pages[0]).toContain(`Page 1 of ${pages.length}`);
    expect(pages[pages.length - 1]).toContain(`Page ${pages.length} of ${pages.length}`);
    expect(pages[1]).toContain('Generated by MICO360');
    // every line made it into the document, in order
    const lines = pages.flat().filter((t) => t.startsWith('Line number'));
    expect(lines).toHaveLength(120);
    expect(lines[119]).toContain('Line number 119');
  });

  it('wraps a long word wider than the line by hard-breaking it', () => {
    const doc = new PdfDocument();
    doc.text('x'.repeat(400));
    const runs = inspectPdf(doc.build()).pages[0]!.filter((t) => /^x+$/.test(t));
    expect(runs.length).toBeGreaterThan(1);
    expect(runs.join('')).toBe('x'.repeat(400));
  });

  it('wraps long paragraphs instead of running off the page edge', () => {
    const doc = new PdfDocument();
    const para = 'Parens ( ) and a backslash \\ must not break anything; '.repeat(12).trim();
    doc.text(para);
    const lines = inspectPdf(doc.build()).pages[0]!.filter((t) => !t.startsWith('Page '));
    expect(lines.length).toBeGreaterThan(2);
    expect(lines.join(' ')).toBe(para);
  });

  it('measures bold text as wider than regular for the same string', () => {
    const doc = new PdfDocument();
    expect(doc.textWidth('Meeting', 12, true)).toBeGreaterThan(doc.textWidth('Meeting', 12, false));
  });

  it('parses hex colors to normalized RGB triples', () => {
    expect(hexToRgb('#8B1E1E')).toEqual([139 / 255, 30 / 255, 30 / 255]);
    expect(hexToRgb('not-a-color', [0, 0, 0])).toEqual([0, 0, 0]);
  });

  it('renders a branded header with a vector logo mark (rounded clip, gradient, check stroke)', () => {
    const doc = new PdfDocument({ palette: { brand: '#0057B8' } });
    doc.brandHeader({ eyebrow: 'Minutes of Meeting', title: 'Acme Tasks', subtitle: 'Get it done' });
    const buf = doc.build();
    const { pages, contents, objects } = inspectPdf(buf);
    expect(pages[0]).toEqual(expect.arrayContaining(['MINUTES OF MEETING', 'Acme Tasks', 'Get it done']));
    const content = contents[0]!;
    expect(content).toMatch(/ c\n/); // bezier corners of the rounded tile
    expect(content).toMatch(/W n/); // clip for the gradient fill
    expect(content).toMatch(/1 1 1 SCN/); // white check stroke
    // the brand color (#0057B8 → 0 0.341 0.722) drives the eyebrow + brand rule fill
    expect(content).toMatch(/0 0\.34\d* 0\.72\d* scn/);
    expect([...objects.values()].some((d) => /\/ShadingType 2/.test(d))).toBe(true); // axial gradient
  });

  it('builds idempotently', () => {
    const doc = new PdfDocument();
    doc.text('Once');
    expect(doc.build()).toBe(doc.build());
  });
});

describe('PdfDocument.table', () => {
  const columns = [{ header: 'Project' }, { header: 'Total' }];

  it('paginates long tables, repeating the header on every page and keeping every row', () => {
    const rows = Array.from({ length: 150 }, (_, i) => [i % 2 ? `مشروع رقم ${i}` : `Project ${i}`, String(i)]);
    const doc = new PdfDocument();
    doc.table(columns, rows);
    const { pages } = inspectPdf(doc.build());
    expect(pages.length).toBeGreaterThanOrEqual(3);
    for (const p of pages) expect(p.slice(0, 2)).toEqual(['Project', 'Total']);
    const cells = pages.flat();
    for (let i = 0; i < 150; i++) {
      expect(cells).toContain(i % 2 ? `مشروع رقم ${i}` : `Project ${i}`);
      expect(cells).toContain(String(i));
    }
  });

  it('wraps a long cell inside its column instead of overflowing', () => {
    const long = 'A very long description that certainly does not fit on a single line of a narrow column in the table';
    const doc = new PdfDocument();
    doc.table([{ header: 'Id' }, { header: 'Description' }, { header: 'Owner' }], [['1', long + ' ' + long, 'Ada']]);
    const cells = inspectPdf(doc.build()).pages[0]!;
    const descLines = cells.filter((t) => !['Id', 'Description', 'Owner', '1', 'Ada', 'Page 1 of 1'].includes(t));
    expect(descLines.length).toBeGreaterThan(1);
    expect(descLines.join(' ')).toBe(long + ' ' + long);
  });
});
