/**
 * A small document builder that flows text down A4 pages and breaks to new pages
 * automatically. Built on pdfkit, with every string going through the Unicode text
 * engine in `pdf-text.ts`: embedded Noto Sans + Noto Naskh Arabic fonts, bidi
 * reordering and Arabic shaping. Arabic, English and mixed lines therefore render as
 * real, joined glyphs in the right order; right-to-left paragraphs align to the right
 * edge; long text wraps to the column; tables repeat their header on every page.
 *
 * Rich enough for structured documents (headings, key/value rows, bullet lists,
 * rules, tables) such as meeting minutes and report exports.
 */
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import PDFDocument from 'pdfkit';
import { drawTextLine, layoutText, lineBox, measureText, registerPdfFonts, type TextLine } from './pdf-text';

export type RGB = [number, number, number];

const INK: RGB = [0.11, 0.1, 0.09];
const MUTED: RGB = [0.42, 0.4, 0.38];
const BRAND: RGB = [0.66, 0.12, 0.12];
const LINE: RGB = [0.82, 0.8, 0.78];
const WHITE: RGB = [1, 1, 1];
const DANGER: RGB = [0.72, 0.16, 0.16];
const SUCCESS: RGB = [0.18, 0.49, 0.33];
const WARNING: RGB = [0.72, 0.47, 0.12];

/**
 * The company logo for PDFs: assets/logo-pdf.png, the brand logo flattened onto white (no alpha
 * channel, so pdfkit embeds it synchronously), found next to the server or the source.
 */
let logoCache: Buffer | null | undefined;
function companyLogo(): Buffer | null {
  if (logoCache !== undefined) return logoCache;
  const candidates = [resolve(process.cwd(), 'assets', 'logo-pdf.png'), resolve(__dirname, '../../assets/logo-pdf.png'), resolve(__dirname, '../../../assets/logo-pdf.png')];
  const found = candidates.find((c) => existsSync(c));
  logoCache = found ? readFileSync(found) : null;
  return logoCache;
}
const LOGO_ASPECT = 900 / 423;

/** Parse "#RRGGBB" (or an [r,g,b] 0-1 triple) into an RGB 0-1 triple. */
export function hexToRgb(input: string | RGB, fallback: RGB = INK): RGB {
  if (Array.isArray(input)) return input;
  const m = /^#?([0-9a-f]{6})$/i.exec(input.trim());
  if (!m) return fallback;
  const n = parseInt(m[1]!, 16);
  return [((n >> 16) & 0xff) / 255, ((n >> 8) & 0xff) / 255, (n & 0xff) / 255];
}

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}
function mix(a: RGB, b: RGB, t: number): RGB {
  return [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)];
}
/** Darken an RGB toward black by `amount` (0-1). */
function darken(c: RGB, amount: number): RGB {
  return [c[0] * (1 - amount), c[1] * (1 - amount), c[2] * (1 - amount)];
}
/** RGB 0-1 triple → "#rrggbb" for pdfkit. */
function toHex(c: RGB): string {
  const h = (v: number) =>
    Math.round(Math.min(1, Math.max(0, v)) * 255)
      .toString(16)
      .padStart(2, '0');
  return `#${h(c[0])}${h(c[1])}${h(c[2])}`;
}

/** 'start' = left for left-to-right paragraphs, right for right-to-left (Arabic) ones. */
export type TextAlign = 'start' | 'left' | 'right' | 'center';

/** Paragraph direction; when omitted it follows the first strong character (UAX #9). */
export type TextDirection = 'ltr' | 'rtl';

export interface TextOptions {
  bold?: boolean;
  size?: number;
  color?: RGB;
  /** Indent from the starting edge (left for LTR text, right for RTL text), in points. */
  indent?: number;
  /** Extra vertical space added after the block, in points. */
  gap?: number;
  align?: TextAlign;
  /** Force the paragraph direction (e.g. to align an attribution line with the note above it). */
  direction?: TextDirection;
  /** 'display' sets Latin text in the heading face (Archivo). */
  family?: 'text' | 'display';
}

export interface PdfDocumentOptions {
  /** Small line(s) shown at the bottom-left of every page (e.g. a "generated by" credit). */
  footerLeft?: string;
  /** Brand palette; hex strings or RGB triples. Drives headings, rules, labels and the footer. */
  palette?: Partial<Record<'ink' | 'muted' | 'brand' | 'line', string | RGB>>;
  /** Document title stored in the PDF metadata (shown in viewers' title bars and tabs). */
  title?: string;
  /** A4 portrait (default) or landscape, for wide tables. */
  orientation?: 'portrait' | 'landscape';
  /** Shown with the logo in a slim header at the top of every page after the first. */
  runningTitle?: string;
}

export interface StatTile {
  label: string;
  value: string;
  /** A small note beside the value (e.g. a percentage). */
  note?: string;
  tone?: 'brand' | 'danger' | 'success' | 'warning' | 'muted';
}

export interface BarItem {
  label: string;
  value: number;
  color?: string | RGB;
}

export interface ChartSeries {
  name: string;
  values: number[];
  color?: string | RGB;
}

export interface TableColumn {
  /** Header text. */
  header: string;
  /** 'auto' (default): numeric columns right-aligned, text by its own direction. */
  align?: 'auto' | 'left' | 'right';
}

const NUMERIC = /^[-+]?[\d,]*\.?\d+%?$/;

export class PdfDocument {
  readonly pageWidth: number; // A4, the paper size used in Oman
  readonly pageHeight: number;
  readonly margin = 54; // 0.75"
  readonly bottomMargin = 62; // leaves room for the footer
  /** Where content starts on pages after the first when a running header is drawn above it. */
  private readonly continuationTop: number;

  private readonly doc: PDFKit.PDFDocument;
  /** Top-down cursor (pdfkit coordinates): where the next block starts. */
  private y: number;
  private built: Buffer | null = null;
  private builtPages = 0;

  /** Resolved brand palette used by headings, rules, labels and the footer. */
  private readonly pal: { ink: RGB; muted: RGB; brand: RGB; line: RGB };

  constructor(private readonly opts: PdfDocumentOptions = {}) {
    const landscape = opts.orientation === 'landscape';
    this.pageWidth = landscape ? 841.89 : 595.28;
    this.pageHeight = landscape ? 595.28 : 841.89;
    this.continuationTop = opts.runningTitle ? this.margin + 14 : this.margin;
    const p = opts.palette ?? {};
    this.pal = {
      ink: p.ink ? hexToRgb(p.ink, INK) : INK,
      muted: p.muted ? hexToRgb(p.muted, MUTED) : MUTED,
      brand: p.brand ? hexToRgb(p.brand, BRAND) : BRAND,
      line: p.line ? hexToRgb(p.line, LINE) : LINE,
    };
    this.doc = new PDFDocument({
      size: 'A4',
      layout: landscape ? 'landscape' : 'portrait',
      margin: 0,
      bufferPages: true, // footers ("Page N of M") are drawn once the page count is known
      displayTitle: Boolean(opts.title),
      info: opts.title ? { Title: opts.title } : {},
    });
    registerPdfFonts(this.doc);
    this.y = this.margin;
  }

  private get contentWidth(): number {
    return this.pageWidth - this.margin * 2;
  }

  private get contentBottom(): number {
    return this.pageHeight - this.bottomMargin;
  }

  /** Number of pages so far (the final count once built). */
  get pageCount(): number {
    return this.built ? this.builtPages : this.doc.bufferedPageRange().count;
  }

  private newPage(): void {
    this.doc.addPage({ size: 'A4', layout: this.opts.orientation === 'landscape' ? 'landscape' : 'portrait', margin: 0 });
    this.y = this.continuationTop;
  }

  /** Room left on the current page, in points. */
  get remaining(): number {
    return this.contentBottom - this.y;
  }

  /** Keep the next `height` points together: start a new page if they don't fit here. */
  keepTogether(height: number): this {
    this.ensure(height);
    return this;
  }

  /** Start a new page unless `height` still fits (never loops on an over-tall block at a page top). */
  private ensure(height: number): void {
    if (this.y + height > this.contentBottom && this.y > this.continuationTop + 0.5) this.newPage();
  }

  /** Width of a string in points at the given size/weight (shaped, so Arabic joins are measured correctly). */
  textWidth(text: string, size: number, bold = false): number {
    return measureText(text, size, bold);
  }

  private fillRect(x: number, top: number, w: number, h: number, color: RGB): void {
    this.doc.rect(x, top, w, h).fill(toHex(color));
  }

  /** Draw a laid-out line on `baseline`, aligned inside [left, left + width]. */
  private placeLine(line: TextLine, left: number, width: number, baseline: number, size: number, color: RGB, align: TextAlign): void {
    const effective = align === 'start' ? (line.rtl ? 'right' : 'left') : align;
    const x = effective === 'right' ? left + width - line.width : effective === 'center' ? left + (width - line.width) / 2 : left;
    drawTextLine(this.doc, line, x, baseline, size, toHex(color));
  }

  /** Draw the brand logo mark: a rounded gradient tile with a white check + progress dot. `y` is the tile's bottom edge in PDF (bottom-up) space. */
  logoMark(x: number, y: number, size: number, from?: RGB, to?: RGB): this {
    const c0 = from ?? this.pal.brand;
    const c1 = to ?? darken(this.pal.brand, 0.4);
    const top = this.pageHeight - y - size;
    const r = size * 0.22;
    const grad = this.doc.linearGradient(x, top, x, top + size);
    grad.stop(0, toHex(c0)).stop(1, toHex(c1));
    this.doc.save();
    this.doc.roundedRect(x, top, size, size, r).clip();
    this.doc.rect(x, top, size, size).fill(grad);
    this.doc.restore();
    // White check mark (stroked, round caps).
    this.doc
      .save()
      .lineWidth(size * 0.1)
      .lineCap('round')
      .lineJoin('round')
      .moveTo(x + size * 0.27, top + size * 0.5)
      .lineTo(x + size * 0.43, top + size * 0.66)
      .lineTo(x + size * 0.72, top + size * 0.36)
      .stroke(toHex(WHITE))
      .restore();
    // Small white progress node at the top-right.
    this.doc.circle(x + size * 0.72, top + size * 0.26, size * 0.07).fill(toHex(WHITE));
    return this;
  }

  /**
   * A branded document header: the logo mark, product name + tagline, an eyebrow label,
   * and a brand rule beneath. Positions itself from the current cursor and advances past it.
   */
  brandHeader(opts: { title: string; subtitle?: string; eyebrow?: string; from?: RGB; to?: RGB }): this {
    const s = 42;
    const top = this.y;
    this.logoMark(this.margin, this.pageHeight - top - s, s, opts.from, opts.to);
    const tx = this.margin + s + 14;
    const tw = this.contentWidth - s - 14;
    const one = (text: string, size: number, bold: boolean): TextLine => layoutText(text, { size, bold, maxWidth: tw })[0]!;
    if (opts.eyebrow) drawTextLine(this.doc, one(opts.eyebrow.toUpperCase(), 8, true), tx, top + 9, 8, toHex(this.pal.brand));
    drawTextLine(this.doc, one(opts.title, 17, true), tx, top + 27, 17, toHex(this.pal.ink));
    if (opts.subtitle) drawTextLine(this.doc, one(opts.subtitle, 9, false), tx, top + 39, 9, toHex(this.pal.muted));
    this.y = top + s + 10;
    this.fillRect(this.margin, this.y, this.contentWidth, 2, this.pal.brand);
    this.y += 2 + 12;
    return this;
  }

  /** Add empty vertical space (points). At a page break the space is dropped rather than carried over. */
  spacer(height: number): this {
    if (this.y + height > this.contentBottom) this.newPage();
    else this.y += height;
    return this;
  }

  /** A flowing paragraph; honors embedded "\n", wraps to the content width, aligns RTL paragraphs right. */
  text(content: string, options: TextOptions = {}): this {
    const size = options.size ?? 10.5;
    const color = options.color ?? this.pal.ink;
    const indent = options.indent ?? 0;
    const width = this.contentWidth - indent;
    for (const line of layoutText(content, { size, bold: options.bold ?? false, maxWidth: width, direction: options.direction, family: options.family })) {
      const box = lineBox(line, size);
      this.ensure(box.height);
      this.placeLine(line, line.rtl ? this.margin : this.margin + indent, width, this.y + box.ascent, size, color, options.align ?? 'start');
      this.y += box.height;
    }
    if (options.gap) this.y += options.gap;
    return this;
  }

  /** A section heading: bold, slightly larger, with a hairline rule beneath. Kept with what follows it. */
  heading(text: string, options: { size?: number; color?: RGB; topGap?: number; keepWith?: number } = {}): this {
    const size = options.size ?? 12.5;
    this.spacer(options.topGap ?? 14);
    // Heading + rule + the start of what follows (at least two lines, or `keepWith` points).
    this.ensure(size * 1.8 + 9 + Math.max(32, Math.min(options.keepWith ?? 0, this.contentBottom - this.continuationTop - size * 1.8 - 9)));
    this.text(text, { bold: true, size, color: options.color ?? this.pal.brand, family: 'display' });
    this.y += 3;
    this.fillRect(this.margin, this.y, this.contentWidth, 0.7, this.pal.line);
    this.y += 6;
    return this;
  }

  /**
   * A "Label: value" row; the value wraps under a hanging indent aligned past the label.
   * A one-line value sits right after its label; a wrapped right-to-left value is set
   * flush right like any Arabic paragraph.
   */
  keyValue(label: string, value: string, options: { size?: number } = {}): this {
    const size = options.size ?? 10.5;
    const labelLine = layoutText(label, { size, bold: true })[0]!;
    const labelWidth = labelLine.width + size * 0.9;
    const valueWidth = this.contentWidth - labelWidth;
    const valueLines = layoutText(value || '—', { size, maxWidth: valueWidth });
    valueLines.forEach((ln, i) => {
      // Label and first value line share one baseline, even when only one of them is Arabic.
      const box = lineBox(ln, size, ln.arabic || (i === 0 && labelLine.arabic));
      this.ensure(box.height);
      const baseline = this.y + box.ascent;
      if (i === 0) this.placeLine(labelLine, this.margin, labelWidth, baseline, size, this.pal.muted, 'left');
      this.placeLine(ln, this.margin + labelWidth, valueWidth, baseline, size, this.pal.ink, valueLines.length === 1 ? 'left' : 'start');
      this.y += box.height;
    });
    return this;
  }

  /** A bullet list item with a hanging indent; a small square marks it (on the right for RTL items). */
  bullet(content: string, options: { indent?: number; color?: RGB; size?: number; direction?: TextDirection } = {}): this {
    const size = options.size ?? 10.5;
    const indent = options.indent ?? 0;
    const marker = 12;
    const width = this.contentWidth - indent - marker;
    const lines = layoutText(content, { size, maxWidth: width, direction: options.direction });
    const rtl = lines[0]?.rtl ?? false;
    lines.forEach((ln, i) => {
      const box = lineBox(ln, size);
      this.ensure(box.height);
      const baseline = this.y + box.ascent;
      if (i === 0) {
        const sq = 2.6;
        const sx = rtl ? this.pageWidth - this.margin - indent - 1 - sq : this.margin + indent + 1;
        this.fillRect(sx, baseline - size * 0.28 - sq, sq, sq, options.color ?? this.pal.brand);
      }
      this.placeLine(ln, rtl ? this.margin : this.margin + indent + marker, width, baseline, size, this.pal.ink, 'start');
      this.y += box.height;
    });
    return this;
  }

  /** A numbered list item with a hanging indent aligned past the number (mirrored for RTL items). */
  numbered(marker: string, content: string, options: { indent?: number; size?: number; direction?: TextDirection } = {}): this {
    const size = options.size ?? 10.5;
    const indent = options.indent ?? 0;
    const gutter = Math.max(16, measureText(marker, size, true) + size * 0.3 + 4);
    const width = this.contentWidth - indent - gutter;
    const lines = layoutText(content, { size, maxWidth: width, direction: options.direction });
    const rtl = lines[0]?.rtl ?? false;
    const markerLine = layoutText(marker, { size, bold: true, direction: rtl ? 'rtl' : 'ltr' })[0]!;
    lines.forEach((ln, i) => {
      const box = lineBox(ln, size);
      this.ensure(box.height);
      const baseline = this.y + box.ascent;
      if (i === 0) {
        const mx = rtl ? this.pageWidth - this.margin - indent - markerLine.width : this.margin + indent;
        drawTextLine(this.doc, markerLine, mx, baseline, size, toHex(this.pal.brand));
      }
      this.placeLine(ln, rtl ? this.margin : this.margin + indent + gutter, width, baseline, size, this.pal.ink, 'start');
      this.y += box.height;
    });
    return this;
  }

  /**
   * The report header: the company logo on the left; the title (Archivo), a subtitle and detail
   * lines (generated, filters) on the right; a brand gradient rule beneath.
   */
  reportHeader(opts: { title: string; subtitle?: string; details?: string[] }): this {
    const top = this.y;
    const logo = companyLogo();
    const logoH = 40;
    const logoW = logo ? logoH * LOGO_ASPECT : logoH;
    if (logo) this.doc.image(logo, this.margin, top, { height: logoH });
    else this.logoMark(this.margin, this.pageHeight - top - logoH, logoH);
    const blockLeft = this.margin + logoW + 24;
    const blockWidth = this.pageWidth - this.margin - blockLeft;
    let by = top;
    const right = (text: string, size: number, color: RGB, opts2: { bold?: boolean; family?: 'text' | 'display' } = {}) => {
      for (const ln of layoutText(text, { size, bold: opts2.bold, family: opts2.family, maxWidth: blockWidth })) {
        const box = lineBox(ln, size);
        this.placeLine(ln, blockLeft, blockWidth, by + box.ascent, size, color, 'right');
        by += box.height;
      }
    };
    right(opts.title, 19, this.pal.ink, { bold: true, family: 'display' });
    if (opts.subtitle) right(opts.subtitle, 10.5, this.pal.brand, { bold: true });
    for (const d of opts.details ?? []) right(d, 8.5, this.pal.muted);
    this.y = Math.max(top + logoH, by) + 10;
    // Brand gradient rule (the web app's #A83326 → #8B1E1E → #5E1414 sheen).
    const grad = this.doc.linearGradient(this.margin, 0, this.pageWidth - this.margin, 0);
    grad.stop(0, toHex(mix(this.pal.brand, WHITE, 0.12))).stop(0.55, toHex(this.pal.brand)).stop(1, toHex(darken(this.pal.brand, 0.33)));
    this.doc.rect(this.margin, this.y, this.contentWidth, 2.5).fill(grad);
    this.y += 2.5 + 14;
    return this;
  }

  private tone(t: StatTile['tone']): RGB {
    return t === 'danger' ? DANGER : t === 'success' ? SUCCESS : t === 'warning' ? WARNING : t === 'muted' ? this.pal.muted : this.pal.brand;
  }

  /**
   * A row of summary tiles: a big value (Archivo) over its label, with a coloured accent. A note
   * sits beside the value when it fits there, otherwise on its own line(s) under the label — it is
   * never cut short. All tiles in the row share the tallest tile's height.
   */
  statTiles(items: StatTile[]): this {
    if (items.length === 0) return this;
    const gap = 10;
    const w = (this.contentWidth - gap * (items.length - 1)) / items.length;
    const inner = w - 20;
    const laid = items.map((it) => {
      // The value shrinks (19 → 11 pt) until it fits on one line, and wraps only if it still doesn't.
      let size = 19;
      while (size > 11 && measureText(it.value, size, true, 'display') > inner) size -= 1;
      const values = layoutText(it.value, { size, bold: true, family: 'display', maxWidth: inner });
      const value = values[0]!;
      const noteWidth = it.note ? measureText(it.note, 9, true) : 0;
      const beside = !it.note || (values.length === 1 && value.width + 6 + noteWidth <= inner);
      const label = layoutText(it.label, { size: 8.5, maxWidth: inner });
      const note = it.note && !beside ? layoutText(it.note, { size: 8.5, bold: true, maxWidth: inner }) : [];
      const extra = (values.length - 1) * size * 1.15;
      return { it, size, values, value, beside, label, note, extra };
    });
    const h = Math.max(56, ...laid.map((l) => 36 + l.extra + 11 * l.label.length + 11 * l.note.length + 6));
    this.ensure(h + 8);
    const top = this.y;
    laid.forEach(({ it, size, values, value, beside, label, note, extra }, i) => {
      const x = this.margin + i * (w + gap);
      const accent = this.tone(it.tone);
      this.doc.roundedRect(x, top, w, h, 6).fill(toHex(mix(accent, WHITE, 0.93)));
      this.doc.save();
      this.doc.roundedRect(x, top, w, h, 6).clip();
      this.fillRect(x, top, 3, h, accent);
      this.doc.restore();
      values.forEach((ln, li) => drawTextLine(this.doc, ln, x + 12, top + 26 + li * size * 1.15, size, toHex(it.tone === 'danger' ? DANGER : this.pal.ink)));
      if (it.note && beside) {
        const n = layoutText(it.note, { size: 9, bold: true })[0]!;
        drawTextLine(this.doc, n, x + 12 + value.width + 6, top + 26, 9, toHex(accent));
      }
      let ly = top + 44 + extra;
      for (const ln of label) {
        drawTextLine(this.doc, ln, x + 12, ly, 8.5, toHex(this.pal.muted));
        ly += 11;
      }
      for (const ln of note) {
        drawTextLine(this.doc, ln, x + 12, ly, 8.5, toHex(accent));
        ly += 11;
      }
    });
    this.y = top + h + 8;
    return this;
  }

  /** Horizontal bars, one per item, scaled to the largest value; each row is kept whole. */
  barList(items: BarItem[], options: { size?: number } = {}): this {
    const size = options.size ?? 9;
    const rowH = 17;
    const labelW = Math.min(170, Math.max(...items.map((it) => measureText(it.label, size)), 40) + 10);
    const valueW = Math.max(...items.map((it) => measureText(String(it.value), size, true)), 14) + 8;
    const barMax = this.contentWidth - labelW - valueW - 6;
    const max = Math.max(...items.map((it) => it.value), 1);
    for (const it of items) {
      this.ensure(rowH);
      const box = lineBox(null, size, true);
      const baseline = this.y + (rowH - box.height) / 2 + box.ascent;
      const label = layoutText(it.label, { size, maxWidth: labelW - 10 })[0];
      if (label) this.placeLine(label, this.margin, labelW - 10, baseline, size, this.pal.ink, 'left');
      const bx = this.margin + labelW;
      this.fillRect(bx, this.y + 5, barMax, rowH - 10, mix(this.pal.line, WHITE, 0.6));
      const bw = (barMax * Math.max(0, it.value)) / max;
      if (bw > 0) this.fillRect(bx, this.y + 5, Math.max(bw, 1.5), rowH - 10, it.color ? hexToRgb(it.color, this.pal.brand) : this.pal.brand);
      const v = layoutText(String(it.value), { size, bold: true })[0]!;
      drawTextLine(this.doc, v, this.pageWidth - this.margin - v.width, baseline, size, toHex(this.pal.ink));
      this.y += rowH;
    }
    this.y += 4;
    return this;
  }

  /** A line chart with a legend, a value axis with gridlines and first/middle/last day labels. Kept whole on one page. */
  lineChart(opts: { labels: string[]; series: ChartSeries[]; height?: number }): this {
    const height = opts.height ?? 170;
    const legendH = 24;
    this.ensure(height + legendH + 6);
    const defaults: RGB[] = [this.pal.ink, this.pal.brand, WARNING, SUCCESS];
    const colors = opts.series.map((s, i) => (s.color ? hexToRgb(s.color, defaults[i % defaults.length]!) : defaults[i % defaults.length]!));
    // Legend.
    let lx = this.margin;
    opts.series.forEach((s, i) => {
      this.fillRect(lx, this.y + 4, 9, 9, colors[i]!);
      const name = layoutText(s.name, { size: 8.5 })[0]!;
      drawTextLine(this.doc, name, lx + 13, this.y + 12, 8.5, toHex(this.pal.ink));
      lx += 13 + name.width + 16;
    });
    this.y += legendH;
    const top = this.y;
    const max = Math.max(1, ...opts.series.flatMap((s) => s.values));
    const step = [1, 2, 5, 10, 20, 25, 50, 100, 200, 250, 500, 1000, 2000, 5000].find((st) => st * 4 >= max) ?? Math.ceil(max / 4);
    const yMax = step * 4;
    const axisW = Math.max(measureText(String(yMax), 8), 10) + 8;
    const left = this.margin + axisW;
    const plotW = this.contentWidth - axisW;
    const plotH = height - 16;
    const yOf = (v: number) => top + plotH - (plotH * v) / yMax;
    for (let g = 0; g <= 4; g++) {
      const gy = yOf(g * step);
      this.fillRect(left, gy, plotW, 0.5, g === 0 ? this.pal.muted : mix(this.pal.line, WHITE, 0.3));
      const t = layoutText(String(g * step), { size: 8 })[0]!;
      drawTextLine(this.doc, t, left - 6 - t.width, gy + 3, 8, toHex(this.pal.muted));
    }
    const n = opts.labels.length;
    const xOf = (i: number) => (n <= 1 ? left + plotW / 2 : left + (plotW * i) / (n - 1));
    opts.series.forEach((s, si) => {
      const pts = s.values.map((v, i) => [xOf(i), yOf(Math.max(0, v))] as const);
      if (pts.length === 0) return;
      this.doc.save().lineWidth(1.6).lineJoin('round').lineCap('round');
      this.doc.moveTo(pts[0]![0], pts[0]![1]);
      for (const [x, y] of pts.slice(1)) this.doc.lineTo(x, y);
      if (pts.length === 1) this.doc.lineTo(pts[0]![0] + 0.1, pts[0]![1]);
      this.doc.stroke(toHex(colors[si]!)).restore();
      if (pts.length <= 31) for (const [x, y] of pts) this.doc.circle(x, y, 1.6).fill(toHex(colors[si]!));
    });
    const marks = n <= 1 ? [0] : [...new Set([0, Math.floor((n - 1) / 2), n - 1])];
    for (const i of marks) {
      const t = layoutText(opts.labels[i] ?? '', { size: 8 })[0];
      if (!t) continue;
      const x = Math.min(Math.max(xOf(i) - t.width / 2, left), this.pageWidth - this.margin - t.width);
      drawTextLine(this.doc, t, x, top + plotH + 12, 8, toHex(this.pal.muted));
    }
    this.y = top + height + 6;
    return this;
  }

  /** A full-width hairline rule. */
  rule(color?: RGB): this {
    this.spacer(4);
    this.ensure(4);
    this.fillRect(this.margin, this.y, this.contentWidth, 0.6, color ?? this.pal.line);
    this.y += 4;
    return this;
  }

  /**
   * A data table spanning the content width. Columns are sized from their content,
   * cells wrap within their column, rows never split across pages, and the header row
   * repeats at the top of every page. Numeric columns align right; text cells align to
   * their own direction (Arabic right, English left).
   */
  table(
    columns: TableColumn[],
    rows: ReadonlyArray<ReadonlyArray<string>>,
    options: { size?: number; cellColor?: (row: number, col: number) => RGB | null } = {},
  ): this {
    const n = columns.length;
    if (n === 0) return this;
    const layout = this.tableLayout(columns, rows, options.size ?? 8.5);
    const { size, padX, padY, total, box, widths, numeric, header, body } = layout;

    const drawRow = (row: { laid: TextLine[][]; height: number }, fill: RGB | null, ri: number | null) => {
      if (fill) this.fillRect(this.margin, this.y, total, row.height, fill);
      let x = this.margin;
      row.laid.forEach((lines, ci) => {
        const color = (ri !== null && options.cellColor?.(ri, ci)) || this.pal.ink;
        lines.forEach((ln, li) => {
          const baseline = this.y + padY + li * box.height + box.ascent;
          this.placeLine(ln, x + padX, widths[ci]! - padX * 2, baseline, size, color, numeric[ci] ? 'right' : 'start');
        });
        x += widths[ci]!;
      });
      this.fillRect(this.margin, this.y + row.height - 0.5, total, 0.5, this.pal.line);
      this.y += row.height;
    };

    const headerFill = mix(this.pal.brand, WHITE, 0.9);
    const stripe = mix(this.pal.line, WHITE, 0.72);
    this.ensure(header.height + (body[0]?.height ?? 0));
    drawRow(header, headerFill, null);
    body.forEach((row, ri) => {
      if (this.y + row.height > this.contentBottom) {
        this.newPage();
        drawRow(header, headerFill, null); // repeat the header on every page
      }
      drawRow(row, ri % 2 === 1 ? stripe : null, ri);
    });
    return this;
  }

  /** The height a table would take if drawn now on one page (header + every row), in points. */
  tableHeight(columns: TableColumn[], rows: ReadonlyArray<ReadonlyArray<string>>, options: { size?: number } = {}): number {
    if (columns.length === 0) return 0;
    const { header, body } = this.tableLayout(columns, rows, options.size ?? 8.5);
    return header.height + body.reduce((s, r) => s + r.height, 0);
  }

  private tableLayout(columns: TableColumn[], rows: ReadonlyArray<ReadonlyArray<string>>, size: number) {
    const n = columns.length;
    const padX = 5;
    const padY = 3;
    const total = this.contentWidth;
    // One line height for every cell (Arabic-safe), so baselines line up across a row
    // and every row has the same rhythm whether or not it contains Arabic.
    const box = lineBox(null, size, true);

    // Column widths: natural single-line widths, stretched to fill or water-filled to fit.
    const natural = columns.map((c, ci) => {
      let w = measureText(c.header, size, true);
      for (const r of rows) w = Math.max(w, measureText(r[ci] ?? '', size));
      return Math.max(w + padX * 2, 30);
    });
    const naturalSum = natural.reduce((a, b) => a + b, 0);
    const widths = new Array<number>(n).fill(0);
    if (naturalSum <= total) {
      natural.forEach((w, i) => (widths[i] = w + (total - naturalSum) * (w / naturalSum)));
    } else {
      // Columns narrower than a fair share keep their natural width; the rest split what is left.
      let open = natural.map((_, i) => i);
      let remaining = total;
      while (open.length > 0) {
        const fair = remaining / open.length;
        const small = open.filter((i) => natural[i]! <= fair);
        if (small.length === 0) {
          open.forEach((i) => (widths[i] = fair));
          break;
        }
        for (const i of small) {
          widths[i] = natural[i]!;
          remaining -= natural[i]!;
        }
        open = open.filter((i) => natural[i]! > fair);
      }
    }

    const numeric = columns.map((c, ci) => {
      if (c.align === 'right') return true;
      if (c.align === 'left') return false;
      const vals = rows.map((r) => (r[ci] ?? '').trim()).filter((v) => v.length > 0);
      return vals.length > 0 && vals.every((v) => NUMERIC.test(v));
    });

    // Never let one row outgrow a page: an absurdly tall cell is cut to what fits.
    const maxLines = Math.max(1, Math.floor((this.contentBottom - this.margin - 3 * box.height - padY * 4) / box.height));
    const layoutRow = (cells: ReadonlyArray<string>, bold: boolean) => {
      const laid = columns.map((_, ci) => layoutText(cells[ci] ?? '', { size, bold, maxWidth: widths[ci]! - padX * 2 }).slice(0, maxLines));
      return { laid, height: Math.max(...laid.map((l) => l.length)) * box.height + padY * 2 };
    };

    const header = layoutRow(
      columns.map((c) => c.header),
      true,
    );
    const body = rows.map((r) => layoutRow(r, false));
    return { size, padX, padY, total, box, widths, numeric, header, body };
  }

  /** Serialize to a PDF byte buffer (idempotent). */
  build(): Buffer {
    if (this.built) return this.built;
    const range = this.doc.bufferedPageRange();
    const total = range.count;
    const footerLines = (this.opts.footerLeft ?? '').split('\n').filter((l) => l.length > 0);
    const { line, muted, brand } = this.pal;

    const logo = this.opts.runningTitle ? companyLogo() : null;
    for (let i = 0; i < total; i++) {
      this.doc.switchToPage(range.start + i);
      if (i > 0 && this.opts.runningTitle) {
        // Slim running header: small logo, the document title on the right, a hairline.
        const h = 16;
        if (logo) this.doc.image(logo, this.margin, 26, { height: h });
        else this.logoMark(this.margin, this.pageHeight - 26 - h, h);
        const t = layoutText(this.opts.runningTitle, { size: 8, maxWidth: this.contentWidth - h * LOGO_ASPECT - 20 })[0]!;
        drawTextLine(this.doc, t, this.pageWidth - this.margin - t.width, 37, 8, toHex(muted));
        this.fillRect(this.margin, 48, this.contentWidth, 0.6, line);
      }
      // Footer: hairline (with a short brand accent at the left) + credit lines + page number.
      const ruleTop = this.pageHeight - 46;
      this.fillRect(this.margin, ruleTop + 1, this.contentWidth, 0.6, line);
      this.fillRect(this.margin, ruleTop, 40, 1.6, brand);
      const pageLine = layoutText(`Page ${i + 1} of ${total}`, { size: 8 })[0]!;
      const leftWidth = this.contentWidth - pageLine.width - 12;
      footerLines.forEach((text, li) => {
        // The footer is a left-aligned block: lay each line out left-to-right (Arabic runs still read RTL).
        const ln = layoutText(text, { size: 8, maxWidth: leftWidth, direction: 'ltr' })[0]!;
        drawTextLine(this.doc, ln, this.margin, this.pageHeight - 34 + li * 10.5, 8, toHex(muted));
      });
      drawTextLine(this.doc, pageLine, this.pageWidth - this.margin - pageLine.width, this.pageHeight - 34, 8, toHex(muted));
    }

    this.builtPages = total;
    this.doc.end();
    // pdfkit writes the whole file synchronously during end(); drain the stream buffer.
    const chunks: Buffer[] = [];
    for (let c = this.doc.read() as Buffer | null; c !== null; c = this.doc.read() as Buffer | null) chunks.push(c);
    this.built = Buffer.concat(chunks);
    return this.built;
  }
}
