import { describe, it, expect } from 'vitest';
import { PdfDocument, hexToRgb } from './pdf-document';

describe('PdfDocument', () => {
  it('produces a valid PDF envelope with a font resource', () => {
    const doc = new PdfDocument();
    doc.heading('Minutes').text('Hello world');
    const pdf = doc.build().toString('latin1');
    expect(pdf.startsWith('%PDF-1.')).toBe(true);
    expect(pdf.trimEnd().endsWith('%%EOF')).toBe(true);
    expect(pdf).toContain('/BaseFont /Helvetica');
    expect(pdf).toContain('/BaseFont /Helvetica-Bold');
    expect(pdf).toContain('(Hello world) Tj');
  });

  it('flows onto multiple pages and numbers them "Page N of M"', () => {
    const doc = new PdfDocument({ footerLeft: 'Generated by MICO360' });
    for (let i = 0; i < 120; i++) doc.text(`Line number ${i} with enough text to take vertical room on the page.`);
    const pdf = doc.build().toString('latin1');
    const count = Number(pdf.match(/\/Count (\d+)/)![1]);
    expect(count).toBeGreaterThan(1);
    expect(pdf).toContain('(Page 1 of ' + count + ') Tj');
    expect(pdf).toContain('(Generated by MICO360) Tj');
  });

  it('writes an xref whose offsets actually point at each object', () => {
    const doc = new PdfDocument();
    doc.heading('Section').bullet('One').bullet('Two').keyValue('Owner', 'Ada Lovelace');
    const pdf = doc.build().toString('latin1');
    const startxref = Number(pdf.match(/startxref\s+(\d+)/)![1]);
    expect(pdf.slice(startxref, startxref + 4)).toBe('xref');
    const offsets = [...pdf.matchAll(/^(\d{10}) \d{5} n $/gm)].map((m) => Number(m[1]));
    // catalog, pages, 2 fonts, then one page + one content object for a short doc = 6
    expect(offsets.length).toBe(6);
    offsets.forEach((off, i) => {
      expect(pdf.slice(off, off + `${i + 1} 0 obj`.length)).toBe(`${i + 1} 0 obj`);
    });
  });

  it('declares each content stream /Length equal to the real byte length', () => {
    const doc = new PdfDocument();
    doc.text('Parens ( ) and a backslash \\ must not break the stream length.');
    const pdf = doc.build().toString('latin1');
    const m = pdf.match(/<< \/Length (\d+) >>\nstream\n([\s\S]*?)\nendstream/)!;
    const declared = Number(m[1]);
    expect(Buffer.byteLength(m[2]!, 'latin1')).toBe(declared);
  });

  it('wraps a long word wider than the line by hard-breaking it', () => {
    const doc = new PdfDocument();
    const long = 'x'.repeat(400);
    doc.text(long);
    const pdf = doc.build().toString('latin1');
    // the giant token must have been split into multiple Tj runs, not one overflowing line
    const runs = [...pdf.matchAll(/\(x+\) Tj/g)];
    expect(runs.length).toBeGreaterThan(1);
  });

  it('measures bold text as wider than regular for the same string', () => {
    const doc = new PdfDocument();
    expect(doc.textWidth('Meeting', 12, true)).toBeGreaterThan(doc.textWidth('Meeting', 12, false));
  });

  it('parses hex colors to normalized RGB triples', () => {
    expect(hexToRgb('#8B1E1E')).toEqual([139 / 255, 30 / 255, 30 / 255]);
    expect(hexToRgb('not-a-color', [0, 0, 0])).toEqual([0, 0, 0]);
  });

  it('renders a branded header with a vector logo mark (paths + clip + check stroke)', () => {
    const doc = new PdfDocument({ palette: { brand: '#0057B8' } });
    doc.brandHeader({ eyebrow: 'Minutes of Meeting', title: 'Acme Tasks', subtitle: 'Get it done' });
    const pdf = doc.build().toString('latin1');
    expect(pdf).toContain('(MINUTES OF MEETING) Tj');
    expect(pdf).toContain('(Acme Tasks) Tj');
    expect(pdf).toContain(' c\n'); // bezier corners from the rounded logo tile
    expect(pdf).toContain('W\nn'); // clip for the gradient fill
    expect(pdf).toContain('1 1 1 RG'); // white check stroke
    // the custom brand color (#0057B8 → blue ≈ 0.72) drives the eyebrow + brand rule fill
    expect(pdf).toContain('0.72 rg');
  });
});
