/**
 * A small document builder that flows text down A4 pages and breaks to new pages
 * automatically. Built on pdfkit, with every string going through the Unicode text
 * engine in `pdf-text.ts`: embedded Noto Sans + Noto Naskh Arabic fonts, bidi
 * reordering and Arabic shaping. Arabic, English and mixed lines therefore render as
 * real, joined glyphs in the right order; right-to-left paragraphs align to the right
 * edge; long text wraps to the column; tables repeat their header on every page.
 *
 * Rich enough for structured documents (headings, key/value rows, bullet lists,
 * rules, tables) such as meeting minutes and report exports.
 */
import PDFDocument from 'pdfkit';
import { drawTextLine, layoutText, lineBox, measureText, registerPdfFonts, type TextLine } from './pdf-text';

export type RGB = [number, number, number];

const INK: RGB = [0.11, 0.1, 0.09];
const MUTED: RGB = [0.42, 0.4, 0.38];
const BRAND: RGB = [0.66, 0.12, 0.12];
const LINE: RGB = [0.82, 0.8, 0.78];
const WHITE: RGB = [1, 1, 1];

/** Parse "#RRGGBB" (or an [r,g,b] 0-1 triple) into an RGB 0-1 triple. */
export function hexToRgb(input: string | RGB, fallback: RGB = INK): RGB {
  if (Array.isArray(input)) return input;
  const m = /^#?([0-9a-f]{6})$/i.exec(input.trim());
  if (!m) return fallback;
  const n = parseInt(m[1]!, 16);
  return [((n >> 16) & 0xff) / 255, ((n >> 8) & 0xff) / 255, (n & 0xff) / 255];
}

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}
function mix(a: RGB, b: RGB, t: number): RGB {
  return [lerp(a[0], b[0], t), lerp(a[1], b[1], t), lerp(a[2], b[2], t)];
}
/** Darken an RGB toward black by `amount` (0-1). */
function darken(c: RGB, amount: number): RGB {
  return [c[0] * (1 - amount), c[1] * (1 - amount), c[2] * (1 - amount)];
}
/** RGB 0-1 triple → "#rrggbb" for pdfkit. */
function toHex(c: RGB): string {
  const h = (v: number) =>
    Math.round(Math.min(1, Math.max(0, v)) * 255)
      .toString(16)
      .padStart(2, '0');
  return `#${h(c[0])}${h(c[1])}${h(c[2])}`;
}

/** 'start' = left for left-to-right paragraphs, right for right-to-left (Arabic) ones. */
export type TextAlign = 'start' | 'left' | 'right' | 'center';

/** Paragraph direction; when omitted it follows the first strong character (UAX #9). */
export type TextDirection = 'ltr' | 'rtl';

export interface TextOptions {
  bold?: boolean;
  size?: number;
  color?: RGB;
  /** Indent from the starting edge (left for LTR text, right for RTL text), in points. */
  indent?: number;
  /** Extra vertical space added after the block, in points. */
  gap?: number;
  align?: TextAlign;
  /** Force the paragraph direction (e.g. to align an attribution line with the note above it). */
  direction?: TextDirection;
}

export interface PdfDocumentOptions {
  /** Small line(s) shown at the bottom-left of every page (e.g. a "generated by" credit). */
  footerLeft?: string;
  /** Brand palette; hex strings or RGB triples. Drives headings, rules, labels and the footer. */
  palette?: Partial<Record<'ink' | 'muted' | 'brand' | 'line', string | RGB>>;
  /** Document title stored in the PDF metadata (shown in viewers' title bars and tabs). */
  title?: string;
}

export interface TableColumn {
  /** Header text. */
  header: string;
  /** 'auto' (default): numeric columns right-aligned, text by its own direction. */
  align?: 'auto' | 'left' | 'right';
}

const NUMERIC = /^[-+]?[\d,]*\.?\d+%?$/;

export class PdfDocument {
  readonly pageWidth = 595.28; // A4, the paper size used in Oman
  readonly pageHeight = 841.89;
  readonly margin = 54; // 0.75"
  readonly bottomMargin = 62; // leaves room for the footer

  private readonly doc: PDFKit.PDFDocument;
  /** Top-down cursor (pdfkit coordinates): where the next block starts. */
  private y: number;
  private built: Buffer | null = null;
  private builtPages = 0;

  /** Resolved brand palette used by headings, rules, labels and the footer. */
  private readonly pal: { ink: RGB; muted: RGB; brand: RGB; line: RGB };

  constructor(private readonly opts: PdfDocumentOptions = {}) {
    const p = opts.palette ?? {};
    this.pal = {
      ink: p.ink ? hexToRgb(p.ink, INK) : INK,
      muted: p.muted ? hexToRgb(p.muted, MUTED) : MUTED,
      brand: p.brand ? hexToRgb(p.brand, BRAND) : BRAND,
      line: p.line ? hexToRgb(p.line, LINE) : LINE,
    };
    this.doc = new PDFDocument({
      size: 'A4',
      margin: 0,
      bufferPages: true, // footers ("Page N of M") are drawn once the page count is known
      displayTitle: Boolean(opts.title),
      info: opts.title ? { Title: opts.title } : {},
    });
    registerPdfFonts(this.doc);
    this.y = this.margin;
  }

  private get contentWidth(): number {
    return this.pageWidth - this.margin * 2;
  }

  private get contentBottom(): number {
    return this.pageHeight - this.bottomMargin;
  }

  /** Number of pages so far (the final count once built). */
  get pageCount(): number {
    return this.built ? this.builtPages : this.doc.bufferedPageRange().count;
  }

  private newPage(): void {
    this.doc.addPage({ size: 'A4', margin: 0 });
    this.y = this.margin;
  }

  /** Start a new page unless `height` still fits (never loops on an over-tall block at a page top). */
  private ensure(height: number): void {
    if (this.y + height > this.contentBottom && this.y > this.margin + 0.5) this.newPage();
  }

  /** Width of a string in points at the given size/weight (shaped, so Arabic joins are measured correctly). */
  textWidth(text: string, size: number, bold = false): number {
    return measureText(text, size, bold);
  }

  private fillRect(x: number, top: number, w: number, h: number, color: RGB): void {
    this.doc.rect(x, top, w, h).fill(toHex(color));
  }

  /** Draw a laid-out line on `baseline`, aligned inside [left, left + width]. */
  private placeLine(line: TextLine, left: number, width: number, baseline: number, size: number, color: RGB, align: TextAlign): void {
    const effective = align === 'start' ? (line.rtl ? 'right' : 'left') : align;
    const x = effective === 'right' ? left + width - line.width : effective === 'center' ? left + (width - line.width) / 2 : left;
    drawTextLine(this.doc, line, x, baseline, size, toHex(color));
  }

  /** Draw the brand logo mark: a rounded gradient tile with a white check + progress dot. `y` is the tile's bottom edge in PDF (bottom-up) space. */
  logoMark(x: number, y: number, size: number, from?: RGB, to?: RGB): this {
    const c0 = from ?? this.pal.brand;
    const c1 = to ?? darken(this.pal.brand, 0.4);
    const top = this.pageHeight - y - size;
    const r = size * 0.22;
    const grad = this.doc.linearGradient(x, top, x, top + size);
    grad.stop(0, toHex(c0)).stop(1, toHex(c1));
    this.doc.save();
    this.doc.roundedRect(x, top, size, size, r).clip();
    this.doc.rect(x, top, size, size).fill(grad);
    this.doc.restore();
    // White check mark (stroked, round caps).
    this.doc
      .save()
      .lineWidth(size * 0.1)
      .lineCap('round')
      .lineJoin('round')
      .moveTo(x + size * 0.27, top + size * 0.5)
      .lineTo(x + size * 0.43, top + size * 0.66)
      .lineTo(x + size * 0.72, top + size * 0.36)
      .stroke(toHex(WHITE))
      .restore();
    // Small white progress node at the top-right.
    this.doc.circle(x + size * 0.72, top + size * 0.26, size * 0.07).fill(toHex(WHITE));
    return this;
  }

  /**
   * A branded document header: the logo mark, product name + tagline, an eyebrow label,
   * and a brand rule beneath. Positions itself from the current cursor and advances past it.
   */
  brandHeader(opts: { title: string; subtitle?: string; eyebrow?: string; from?: RGB; to?: RGB }): this {
    const s = 42;
    const top = this.y;
    this.logoMark(this.margin, this.pageHeight - top - s, s, opts.from, opts.to);
    const tx = this.margin + s + 14;
    const tw = this.contentWidth - s - 14;
    const one = (text: string, size: number, bold: boolean): TextLine => layoutText(text, { size, bold, maxWidth: tw })[0]!;
    if (opts.eyebrow) drawTextLine(this.doc, one(opts.eyebrow.toUpperCase(), 8, true), tx, top + 9, 8, toHex(this.pal.brand));
    drawTextLine(this.doc, one(opts.title, 17, true), tx, top + 27, 17, toHex(this.pal.ink));
    if (opts.subtitle) drawTextLine(this.doc, one(opts.subtitle, 9, false), tx, top + 39, 9, toHex(this.pal.muted));
    this.y = top + s + 10;
    this.fillRect(this.margin, this.y, this.contentWidth, 2, this.pal.brand);
    this.y += 2 + 12;
    return this;
  }

  /** Add empty vertical space (points). At a page break the space is dropped rather than carried over. */
  spacer(height: number): this {
    if (this.y + height > this.contentBottom) this.newPage();
    else this.y += height;
    return this;
  }

  /** A flowing paragraph; honors embedded "\n", wraps to the content width, aligns RTL paragraphs right. */
  text(content: string, options: TextOptions = {}): this {
    const size = options.size ?? 10.5;
    const color = options.color ?? this.pal.ink;
    const indent = options.indent ?? 0;
    const width = this.contentWidth - indent;
    for (const line of layoutText(content, { size, bold: options.bold ?? false, maxWidth: width, direction: options.direction })) {
      const box = lineBox(line, size);
      this.ensure(box.height);
      this.placeLine(line, line.rtl ? this.margin : this.margin + indent, width, this.y + box.ascent, size, color, options.align ?? 'start');
      this.y += box.height;
    }
    if (options.gap) this.y += options.gap;
    return this;
  }

  /** A section heading: bold, slightly larger, with a hairline rule beneath. Kept with what follows it. */
  heading(text: string, options: { size?: number; color?: RGB; topGap?: number } = {}): this {
    const size = options.size ?? 12.5;
    this.spacer(options.topGap ?? 14);
    this.ensure(size * 1.8 + 9 + 32); // heading + rule + room for at least two lines of content
    this.text(text, { bold: true, size, color: options.color ?? this.pal.brand });
    this.y += 3;
    this.fillRect(this.margin, this.y, this.contentWidth, 0.7, this.pal.line);
    this.y += 6;
    return this;
  }

  /**
   * A "Label: value" row; the value wraps under a hanging indent aligned past the label.
   * A one-line value sits right after its label; a wrapped right-to-left value is set
   * flush right like any Arabic paragraph.
   */
  keyValue(label: string, value: string, options: { size?: number } = {}): this {
    const size = options.size ?? 10.5;
    const labelLine = layoutText(label, { size, bold: true })[0]!;
    const labelWidth = labelLine.width + size * 0.9;
    const valueWidth = this.contentWidth - labelWidth;
    const valueLines = layoutText(value || '—', { size, maxWidth: valueWidth });
    valueLines.forEach((ln, i) => {
      // Label and first value line share one baseline, even when only one of them is Arabic.
      const box = lineBox(ln, size, ln.arabic || (i === 0 && labelLine.arabic));
      this.ensure(box.height);
      const baseline = this.y + box.ascent;
      if (i === 0) this.placeLine(labelLine, this.margin, labelWidth, baseline, size, this.pal.muted, 'left');
      this.placeLine(ln, this.margin + labelWidth, valueWidth, baseline, size, this.pal.ink, valueLines.length === 1 ? 'left' : 'start');
      this.y += box.height;
    });
    return this;
  }

  /** A bullet list item with a hanging indent; a small square marks it (on the right for RTL items). */
  bullet(content: string, options: { indent?: number; color?: RGB; size?: number; direction?: TextDirection } = {}): this {
    const size = options.size ?? 10.5;
    const indent = options.indent ?? 0;
    const marker = 12;
    const width = this.contentWidth - indent - marker;
    const lines = layoutText(content, { size, maxWidth: width, direction: options.direction });
    const rtl = lines[0]?.rtl ?? false;
    lines.forEach((ln, i) => {
      const box = lineBox(ln, size);
      this.ensure(box.height);
      const baseline = this.y + box.ascent;
      if (i === 0) {
        const sq = 2.6;
        const sx = rtl ? this.pageWidth - this.margin - indent - 1 - sq : this.margin + indent + 1;
        this.fillRect(sx, baseline - size * 0.28 - sq, sq, sq, options.color ?? this.pal.brand);
      }
      this.placeLine(ln, rtl ? this.margin : this.margin + indent + marker, width, baseline, size, this.pal.ink, 'start');
      this.y += box.height;
    });
    return this;
  }

  /** A numbered list item with a hanging indent aligned past the number (mirrored for RTL items). */
  numbered(marker: string, content: string, options: { indent?: number; size?: number; direction?: TextDirection } = {}): this {
    const size = options.size ?? 10.5;
    const indent = options.indent ?? 0;
    const gutter = Math.max(16, measureText(marker, size, true) + size * 0.3 + 4);
    const width = this.contentWidth - indent - gutter;
    const lines = layoutText(content, { size, maxWidth: width, direction: options.direction });
    const rtl = lines[0]?.rtl ?? false;
    const markerLine = layoutText(marker, { size, bold: true, direction: rtl ? 'rtl' : 'ltr' })[0]!;
    lines.forEach((ln, i) => {
      const box = lineBox(ln, size);
      this.ensure(box.height);
      const baseline = this.y + box.ascent;
      if (i === 0) {
        const mx = rtl ? this.pageWidth - this.margin - indent - markerLine.width : this.margin + indent;
        drawTextLine(this.doc, markerLine, mx, baseline, size, toHex(this.pal.brand));
      }
      this.placeLine(ln, rtl ? this.margin : this.margin + indent + gutter, width, baseline, size, this.pal.ink, 'start');
      this.y += box.height;
    });
    return this;
  }

  /** A full-width hairline rule. */
  rule(color?: RGB): this {
    this.spacer(4);
    this.ensure(4);
    this.fillRect(this.margin, this.y, this.contentWidth, 0.6, color ?? this.pal.line);
    this.y += 4;
    return this;
  }

  /**
   * A data table spanning the content width. Columns are sized from their content,
   * cells wrap within their column, rows never split across pages, and the header row
   * repeats at the top of every page. Numeric columns align right; text cells align to
   * their own direction (Arabic right, English left).
   */
  table(columns: TableColumn[], rows: ReadonlyArray<ReadonlyArray<string>>, options: { size?: number } = {}): this {
    const n = columns.length;
    if (n === 0) return this;
    const size = options.size ?? 8.5;
    const padX = 5;
    const padY = 3;
    const total = this.contentWidth;
    // One line height for every cell (Arabic-safe), so baselines line up across a row
    // and every row has the same rhythm whether or not it contains Arabic.
    const box = lineBox(null, size, true);

    // Column widths: natural single-line widths, stretched to fill or water-filled to fit.
    const natural = columns.map((c, ci) => {
      let w = measureText(c.header, size, true);
      for (const r of rows) w = Math.max(w, measureText(r[ci] ?? '', size));
      return Math.max(w + padX * 2, 30);
    });
    const naturalSum = natural.reduce((a, b) => a + b, 0);
    const widths = new Array<number>(n).fill(0);
    if (naturalSum <= total) {
      natural.forEach((w, i) => (widths[i] = w + (total - naturalSum) * (w / naturalSum)));
    } else {
      // Columns narrower than a fair share keep their natural width; the rest split what is left.
      let open = natural.map((_, i) => i);
      let remaining = total;
      while (open.length > 0) {
        const fair = remaining / open.length;
        const small = open.filter((i) => natural[i]! <= fair);
        if (small.length === 0) {
          open.forEach((i) => (widths[i] = fair));
          break;
        }
        for (const i of small) {
          widths[i] = natural[i]!;
          remaining -= natural[i]!;
        }
        open = open.filter((i) => natural[i]! > fair);
      }
    }

    const numeric = columns.map((c, ci) => {
      if (c.align === 'right') return true;
      if (c.align === 'left') return false;
      const vals = rows.map((r) => (r[ci] ?? '').trim()).filter((v) => v.length > 0);
      return vals.length > 0 && vals.every((v) => NUMERIC.test(v));
    });

    // Never let one row outgrow a page: an absurdly tall cell is cut to what fits.
    const maxLines = Math.max(1, Math.floor((this.contentBottom - this.margin - 3 * box.height - padY * 4) / box.height));
    const layoutRow = (cells: ReadonlyArray<string>, bold: boolean) => {
      const laid = columns.map((_, ci) => layoutText(cells[ci] ?? '', { size, bold, maxWidth: widths[ci]! - padX * 2 }).slice(0, maxLines));
      return { laid, height: Math.max(...laid.map((l) => l.length)) * box.height + padY * 2 };
    };

    const drawRow = (row: { laid: TextLine[][]; height: number }, fill: RGB | null) => {
      if (fill) this.fillRect(this.margin, this.y, total, row.height, fill);
      let x = this.margin;
      row.laid.forEach((lines, ci) => {
        lines.forEach((ln, li) => {
          const baseline = this.y + padY + li * box.height + box.ascent;
          this.placeLine(ln, x + padX, widths[ci]! - padX * 2, baseline, size, this.pal.ink, numeric[ci] ? 'right' : 'start');
        });
        x += widths[ci]!;
      });
      this.fillRect(this.margin, this.y + row.height - 0.5, total, 0.5, this.pal.line);
      this.y += row.height;
    };

    const header = layoutRow(
      columns.map((c) => c.header),
      true,
    );
    const headerFill = mix(this.pal.brand, WHITE, 0.9);
    const stripe = mix(this.pal.line, WHITE, 0.72);

    const body = rows.map((r) => layoutRow(r, false));
    this.ensure(header.height + (body[0]?.height ?? 0));
    drawRow(header, headerFill);
    body.forEach((row, ri) => {
      if (this.y + row.height > this.contentBottom) {
        this.newPage();
        drawRow(header, headerFill); // repeat the header on every page
      }
      drawRow(row, ri % 2 === 1 ? stripe : null);
    });
    return this;
  }

  /** Serialize to a PDF byte buffer (idempotent). */
  build(): Buffer {
    if (this.built) return this.built;
    const range = this.doc.bufferedPageRange();
    const total = range.count;
    const footerLines = (this.opts.footerLeft ?? '').split('\n').filter((l) => l.length > 0);
    const { line, muted, brand } = this.pal;

    for (let i = 0; i < total; i++) {
      this.doc.switchToPage(range.start + i);
      // Footer: hairline (with a short brand accent at the left) + credit lines + page number.
      const ruleTop = this.pageHeight - 46;
      this.fillRect(this.margin, ruleTop + 1, this.contentWidth, 0.6, line);
      this.fillRect(this.margin, ruleTop, 40, 1.6, brand);
      const pageLine = layoutText(`Page ${i + 1} of ${total}`, { size: 8 })[0]!;
      const leftWidth = this.contentWidth - pageLine.width - 12;
      footerLines.forEach((text, li) => {
        // The footer is a left-aligned block: lay each line out left-to-right (Arabic runs still read RTL).
        const ln = layoutText(text, { size: 8, maxWidth: leftWidth, direction: 'ltr' })[0]!;
        drawTextLine(this.doc, ln, this.margin, this.pageHeight - 34 + li * 10.5, 8, toHex(muted));
      });
      drawTextLine(this.doc, pageLine, this.pageWidth - this.margin - pageLine.width, this.pageHeight - 34, 8, toHex(muted));
    }

    this.builtPages = total;
    this.doc.end();
    // pdfkit writes the whole file synchronously during end(); drain the stream buffer.
    const chunks: Buffer[] = [];
    for (let c = this.doc.read() as Buffer | null; c !== null; c = this.doc.read() as Buffer | null) chunks.push(c);
    this.built = Buffer.concat(chunks);
    return this.built;
  }
}
